[package]
name = "wasix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.24.2", features = ["full"] }
